[2025-06-11 20:16:47,039] [INFO] [logging in using static token]
[2025-06-11 20:16:49,335] [INFO] [Shard ID None has connected to Gateway (Session ID: f55b81f5b5f997584b98858761ea8f22).]
[2025-06-11 20:17:29,990] [INFO] [logging in using static token]
[2025-06-11 20:17:32,700] [INFO] [Shard ID None has connected to Gateway (Session ID: 74364ac8997ab32550434d124580dc89).]
[2025-06-11 20:18:33,798] [INFO] [logging in using static token]
[2025-06-11 20:18:35,363] [INFO] [Shard ID None has connected to Gateway (Session ID: 3d954e15362c1705ec80fdaaebe31ad9).]
[2025-06-11 20:19:22,819] [INFO] [logging in using static token]
[2025-06-11 20:19:37,842] [INFO] [logging in using static token]
[2025-06-11 20:21:03,962] [INFO] [logging in using static token]
[2025-06-11 20:22:21,941] [INFO] [logging in using static token]
[2025-06-11 20:23:00,063] [INFO] [logging in using static token]
[2025-06-11 20:23:22,803] [INFO] [logging in using static token]
[2025-06-11 20:24:56,724] [INFO] [logging in using static token]
[2025-06-11 20:24:57,981] [INFO] [Shard ID None has connected to Gateway (Session ID: 6fa3906da72b262de2fdca97360cba0e).]
[2025-06-11 20:25:25,596] [INFO] [logging in using static token]
[2025-06-11 20:25:30,111] [INFO] [Shard ID None has connected to Gateway (Session ID: 431465efa01bf2117da6b76b355c67be).]
[2025-06-11 20:35:57,688] [INFO] [logging in using static token]
[2025-06-11 20:35:58,305] [INFO] [General Commands sucessfully loaded!]
[2025-06-11 20:35:58,820] [INFO] [Shard ID None has connected to Gateway (Session ID: 2d0c19df5278ef2d674f8ac09d192205).]
[2025-06-11 20:36:49,974] [INFO] [logging in using static token]
[2025-06-11 20:36:50,624] [INFO] [General Commands sucessfully loaded!]
[2025-06-11 20:36:51,055] [INFO] [Shard ID None has connected to Gateway (Session ID: 3c53eff492543a12fe7032ff968c5c7f).]
[2025-06-11 20:42:13,424] [INFO] [logging in using static token]
[2025-06-11 20:42:40,302] [INFO] [logging in using static token]
[2025-06-11 20:42:54,695] [INFO] [logging in using static token]
[2025-06-11 20:42:55,208] [INFO] [General Commands sucessfully loaded!]
[2025-06-11 20:42:55,639] [INFO] [Shard ID None has connected to Gateway (Session ID: e24cfad062394bf51a97e563f9f0c019).]
[2025-06-11 20:44:24,332] [INFO] [logging in using static token]
[2025-06-11 20:44:24,953] [INFO] [General Commands sucessfully loaded!]
[2025-06-11 20:44:25,458] [INFO] [Shard ID None has connected to Gateway (Session ID: 2a67e4c61b7974f8fd3a8e4870547a87).]
[2025-06-11 20:50:28,486] [INFO] [logging in using static token]
[2025-06-11 20:50:30,820] [INFO] [General Commands sucessfully loaded!]
[2025-06-11 20:50:31,548] [INFO] [Shard ID None has connected to Gateway (Session ID: f5482a7b3678d42ceb52520648b89b39).]
[2025-06-11 20:51:47,794] [INFO] [logging in using static token]
[2025-06-11 20:51:49,586] [INFO] [General Commands sucessfully loaded!]
[2025-06-11 20:51:50,422] [INFO] [Shard ID None has connected to Gateway (Session ID: fb26e22af135e4d1e7d3f247453a0030).]
[2025-06-11 20:52:10,473] [INFO] [logging in using static token]
[2025-06-11 20:52:11,261] [INFO] [General Commands sucessfully loaded!]
[2025-06-11 20:52:11,946] [INFO] [Shard ID None has connected to Gateway (Session ID: 921192ddb5d0dacf3780c0d8c8f76a1e).]
[2025-06-11 20:52:13,955] [INFO] [Logged in as N1X]
[2025-06-11 20:55:10,390] [INFO] [logging in using static token]
[2025-06-11 20:55:11,525] [INFO] [General Commands sucessfully loaded!]
[2025-06-11 20:55:12,318] [INFO] [Shard ID None has connected to Gateway (Session ID: eedf3f54ff7a553360f82b881b656344).]
[2025-06-11 20:55:14,329] [INFO] [Logged in as N1X]
[2025-06-11 20:59:03,251] [INFO] [logging in using static token]
[2025-06-11 20:59:05,136] [INFO] [Shard ID None has connected to Gateway (Session ID: 58545a852b62b05e001f9f4d3d7ac0b2).]
[2025-06-11 20:59:07,148] [INFO] [Logged in as N1X]
[2025-06-11 21:00:11,941] [INFO] [logging in using static token]
[2025-06-11 21:00:15,999] [INFO] [Shard ID None has connected to Gateway (Session ID: d605f6260d88aa7c5ffe9863ceda734e).]
[2025-06-11 21:00:18,423] [INFO] [Logged in as N1X]
[2025-06-11 22:26:35,415] [INFO] [Shard ID None has successfully RESUMED session d605f6260d88aa7c5ffe9863ceda734e.]
[2025-06-11 23:09:17,551] [ERROR] [Attempting a reconnect in 0.86s]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1181, in _wrap_create_connection
    sock = await aiohappyeyeballs.start_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohappyeyeballs\impl.py", line 122, in start_connection
    raise first_exception
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohappyeyeballs\impl.py", line 73, in start_connection
    sock = await _connect_sock(
           ^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    )
    ^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohappyeyeballs\impl.py", line 208, in _connect_sock
    await loop.sock_connect(sock, address)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\asyncio\proactor_events.py", line 726, in sock_connect
    return await self._proactor.connect(sock, address)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\asyncio\windows_events.py", line 804, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\asyncio\windows_events.py", line 600, in finish_connect
    ov.getresult()
    ~~~~~~~~~~~~^^
PermissionError: [WinError 5] Access is denied

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 701, in connect
    self.ws = await asyncio.wait_for(coro, timeout=60.0)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\asyncio\tasks.py", line 507, in wait_for
    return await fut
           ^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\gateway.py", line 375, in from_client
    socket = await client.http.ws_connect(str(url))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\http.py", line 554, in ws_connect
    return await self.__session.ws_connect(url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 1052, in _ws_connect
    resp = await self.request(
           ^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 761, in _request
    resp = await handler(req)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\client.py", line 716, in _connect_and_send_request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        req, traces=traces, timeout=real_timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 598, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1122, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1494, in _create_direct_connection
    raise last_exc
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1463, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<7 lines>...
    )
    ^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\aiohttp\connector.py", line 1204, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host gateway-us-east1-c.discord.gg:443 ssl:default [Access is denied]
[2025-06-11 23:09:18,792] [INFO] [Shard ID None has successfully RESUMED session d605f6260d88aa7c5ffe9863ceda734e.]
[2025-06-11 23:28:10,716] [INFO] [logging in using static token]
[2025-06-11 23:28:11,701] [INFO] [Shard ID None has connected to Gateway (Session ID: 6c21f8eb956bbfe8b7a8149448bb5bd8).]
[2025-06-11 23:28:13,702] [INFO] [Logged in as N1X]
[2025-06-11 23:28:25,639] [ERROR] [Ignoring exception in command kick]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1335, in _actual_conversion
    return converter(argument)
TypeError: 'module' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 1021, in invoke
    await self.prepare(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 938, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 845, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 715, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1444, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1344, in _actual_conversion
    raise BadArgument(f'Converting to "{name}" failed for parameter "{param.name}".') from exc
discord.ext.commands.errors.BadArgument: Converting to "discord.member" failed for parameter "member".
[2025-06-11 23:29:33,140] [ERROR] [Ignoring exception in command kick]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1335, in _actual_conversion
    return converter(argument)
TypeError: 'module' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 1021, in invoke
    await self.prepare(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 938, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 845, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 715, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1444, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1344, in _actual_conversion
    raise BadArgument(f'Converting to "{name}" failed for parameter "{param.name}".') from exc
discord.ext.commands.errors.BadArgument: Converting to "discord.member" failed for parameter "member".
[2025-06-11 23:29:38,975] [INFO] [logging in using static token]
[2025-06-11 23:29:39,963] [INFO] [Shard ID None has connected to Gateway (Session ID: 267dbfef9cb5273a2d2d0893845b7400).]
[2025-06-11 23:29:41,969] [INFO] [Logged in as N1X]
[2025-06-11 23:29:46,669] [ERROR] [Ignoring exception in command kick]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1335, in _actual_conversion
    return converter(argument)
TypeError: 'module' object is not callable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 1021, in invoke
    await self.prepare(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 938, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 845, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 715, in transform
    return await run_converters(ctx, converter, argument, param)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1444, in run_converters
    return await _actual_conversion(ctx, converter, argument, param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\converter.py", line 1344, in _actual_conversion
    raise BadArgument(f'Converting to "{name}" failed for parameter "{param.name}".') from exc
discord.ext.commands.errors.BadArgument: Converting to "discord.member" failed for parameter "member".
[2025-06-11 23:29:55,504] [INFO] [logging in using static token]
[2025-06-11 23:29:56,566] [INFO] [Shard ID None has connected to Gateway (Session ID: b49aa99a3e5c8db9385b8976f27aebe1).]
[2025-06-11 23:29:58,581] [INFO] [Logged in as N1X]
[2025-06-11 23:31:06,985] [INFO] [logging in using static token]
[2025-06-11 23:31:08,051] [INFO] [Shard ID None has connected to Gateway (Session ID: 2ad84c845d7e42d087b7ef7f68954d59).]
[2025-06-11 23:31:10,093] [INFO] [Logged in as N1X]
[2025-06-11 23:32:27,683] [INFO] [logging in using static token]
[2025-06-11 23:32:28,757] [INFO] [Shard ID None has connected to Gateway (Session ID: 7954c1376313078b477e991886a5ca25).]
[2025-06-11 23:32:30,773] [INFO] [Logged in as N1X]
[2025-06-11 23:40:56,638] [INFO] [logging in using static token]
[2025-06-11 23:40:57,588] [INFO] [Shard ID None has connected to Gateway (Session ID: 0850acea1e874591497aa8d39a95e560).]
[2025-06-11 23:40:59,594] [INFO] [Logged in as N1X]
[2025-06-11 23:51:04,097] [INFO] [logging in using static token]
[2025-06-11 23:51:05,045] [INFO] [Shard ID None has connected to Gateway (Session ID: 040aab584193dd7f3a52ed32e1e65b7a).]
[2025-06-11 23:51:07,055] [INFO] [Logged in as N1X]
[2025-06-11 23:51:43,115] [INFO] [logging in using static token]
[2025-06-11 23:51:44,035] [INFO] [Shard ID None has connected to Gateway (Session ID: 543db93cf970de8d26b1a08cd679527b).]
[2025-06-11 23:51:46,055] [INFO] [Logged in as N1X]
[2025-06-12 22:24:05,158] [INFO] [logging in using static token]
[2025-06-12 22:24:06,309] [INFO] [Shard ID None has connected to Gateway (Session ID: ffd6bef32db4f918acfa00fdfbf6ea5c).]
[2025-06-12 22:24:08,318] [INFO] [Logged in as N1X]
[2025-06-12 23:25:20,183] [INFO] [Shard ID None has successfully RESUMED session ffd6bef32db4f918acfa00fdfbf6ea5c.]
[2025-06-12 23:46:53,509] [INFO] [Shard ID None has successfully RESUMED session ffd6bef32db4f918acfa00fdfbf6ea5c.]
[2025-06-14 11:56:26,559] [INFO] [logging in using static token]
[2025-06-14 11:56:27,614] [INFO] [Shard ID None has connected to Gateway (Session ID: dd5962ab66a231f081dd8a8bae252cf5).]
[2025-06-14 11:56:29,617] [INFO] [Logged in as N1X]
[2025-06-14 12:37:47,323] [INFO] [logging in using static token]
[2025-06-14 12:37:48,540] [INFO] [Shard ID None has connected to Gateway (Session ID: 5484636f58cae5d5af5d18796860a3f9).]
[2025-06-14 12:37:50,553] [INFO] [Logged in as N1X]
[2025-06-14 12:39:08,963] [INFO] [logging in using static token]
[2025-06-14 12:39:10,058] [INFO] [Shard ID None has connected to Gateway (Session ID: f84de2af01e5c89aec3ed358a6f9177b).]
[2025-06-14 12:39:12,063] [INFO] [Logged in as N1X]
[2025-06-14 12:42:21,783] [INFO] [logging in using static token]
[2025-06-14 12:42:23,143] [INFO] [Shard ID None has connected to Gateway (Session ID: 43225f6f8b88e2d1939596ee714ab98f).]
[2025-06-14 12:42:25,152] [INFO] [Logged in as N1X]
[2025-06-14 12:42:38,116] [INFO] [logging in using static token]
[2025-06-14 12:42:39,237] [INFO] [Shard ID None has connected to Gateway (Session ID: e3f358aa73aa0bb010295feda7506d87).]
[2025-06-14 12:42:41,299] [INFO] [Logged in as N1X]
[2025-06-14 12:45:24,990] [INFO] [logging in using static token]
[2025-06-14 12:45:26,111] [INFO] [Shard ID None has connected to Gateway (Session ID: 550af851b1bf5de7b329f5b1d5afee19).]
[2025-06-14 12:45:28,121] [INFO] [Logged in as N1X]
[2025-06-14 12:47:53,263] [INFO] [logging in using static token]
[2025-06-14 12:47:54,856] [INFO] [Shard ID None has connected to Gateway (Session ID: 8d189488e3d0c9e71676f564cb0622e0).]
[2025-06-14 12:47:56,862] [INFO] [Logged in as N1X]
[2025-06-14 12:48:14,886] [INFO] [logging in using static token]
[2025-06-14 12:48:16,110] [INFO] [Shard ID None has connected to Gateway (Session ID: 917cd5f0d8dcb76c040bb964b13b2cf5).]
[2025-06-14 12:48:18,122] [INFO] [Logged in as N1X]
[2025-06-14 13:46:07,503] [INFO] [Shard ID None has successfully RESUMED session 917cd5f0d8dcb76c040bb964b13b2cf5.]
[2025-06-14 14:14:33,420] [INFO] [Shard ID None has successfully RESUMED session 917cd5f0d8dcb76c040bb964b13b2cf5.]
[2025-06-14 14:21:30,340] [INFO] [logging in using static token]
[2025-06-14 14:21:31,487] [INFO] [Shard ID None has connected to Gateway (Session ID: e039a6e98dcfd04c892106841dd9e848).]
[2025-06-14 14:21:33,492] [INFO] [Logged in as N1X]
[2025-06-14 14:33:55,254] [INFO] [logging in using static token]
[2025-06-14 14:33:56,560] [INFO] [Shard ID None has connected to Gateway (Session ID: b89c42987976300320b4955561824cd1).]
[2025-06-14 14:33:58,577] [INFO] [Logged in as N1X]
[2025-06-14 14:34:03,443] [WARNING] [rayshiba tried to ban N1X#6743 but lacked permissions.]
[2025-06-14 15:08:08,292] [INFO] [logging in using static token]
[2025-06-14 15:08:35,538] [INFO] [logging in using static token]
[2025-06-14 15:08:36,752] [INFO] [Shard ID None has connected to Gateway (Session ID: 6438700cfe253dc3dadfdc43bb5ef049).]
[2025-06-14 15:08:38,767] [INFO] [Logged in as N1X]
[2025-06-14 15:10:03,611] [INFO] [logging in using static token]
[2025-06-14 15:10:04,785] [INFO] [Shard ID None has connected to Gateway (Session ID: b6df24e2f3c70ea5259509a9dba8845a).]
[2025-06-14 15:10:06,793] [INFO] [Logged in as N1X]
[2025-06-14 15:10:10,162] [ERROR] [Ignoring exception in command None]
discord.ext.commands.errors.CommandNotFound: Command "shiba" is not found
[2025-06-14 15:10:22,434] [INFO] [logging in using static token]
[2025-06-14 15:10:23,517] [INFO] [Shard ID None has connected to Gateway (Session ID: 5e759df02bfaf5b6c8ea206e570a0d8c).]
[2025-06-14 15:10:25,526] [INFO] [Logged in as N1X]
[2025-06-14 15:25:16,713] [INFO] [logging in using static token]
[2025-06-14 15:25:17,808] [INFO] [Shard ID None has connected to Gateway (Session ID: e24da2488b3288142544befff08506fd).]
[2025-06-14 15:25:19,827] [ERROR] [Ignoring exception in on_ready]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\Ray\Desktop\PrivateBot\main.py", line 17, in on_ready
    log(f'Logged in as {bot.user.name}')
    ~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'RootLogger' object is not callable
[2025-06-14 15:27:45,994] [INFO] [logging in using static token]
[2025-06-14 15:27:47,275] [INFO] [Shard ID None has connected to Gateway (Session ID: 5923b3a135147043dd2473793d1f98fb).]
[2025-06-14 15:27:49,280] [INFO] [Logged in as N1X]
[2025-06-14 17:04:07,010] [INFO] [Shard ID None has successfully RESUMED session 5923b3a135147043dd2473793d1f98fb.]
[2025-06-15 14:11:09,920] [INFO] [logging in using static token]
[2025-06-15 14:11:11,096] [INFO] [Shard ID None has connected to Gateway (Session ID: e5ecafb283a3f88927adfb67d92e17b0).]
[2025-06-15 14:11:13,099] [INFO] [Logged in as N1X]
[2025-06-15 14:11:22,183] [INFO] [rayshiba cleared 1 messages in channel test-n1x.]
[2025-06-15 14:11:59,289] [INFO] [logging in using static token]
[2025-06-15 14:12:00,356] [INFO] [Shard ID None has connected to Gateway (Session ID: 32724ba58e70bda547a24e895ef785d7).]
[2025-06-15 14:12:02,359] [INFO] [Logged in as N1X]
[2025-06-15 14:12:15,880] [INFO] [rayshiba cleared 1 messages in channel test-n1x.]
[2025-06-15 14:13:47,764] [INFO] [logging in using static token]
[2025-06-15 14:13:49,036] [INFO] [Shard ID None has connected to Gateway (Session ID: 7a1d1e78e9aa3987820303c80dcf6502).]
[2025-06-15 14:13:51,051] [INFO] [Logged in as N1X]
[2025-06-15 14:15:55,049] [INFO] [rayshiba cleared 2 messages in channel test-n1x.]
[2025-06-15 14:17:55,303] [INFO] [logging in using static token]
[2025-06-15 14:17:56,498] [INFO] [Shard ID None has connected to Gateway (Session ID: c95e41fc1d6858ff6400e6db34e9a99c).]
[2025-06-15 14:17:58,508] [INFO] [Logged in as N1X]
[2025-06-15 14:33:24,837] [INFO] [logging in using static token]
[2025-06-15 14:33:25,904] [INFO] [Shard ID None has connected to Gateway (Session ID: 5d928a70c8711ed623c5c108c7316a67).]
[2025-06-15 14:33:27,908] [INFO] [Logged in as N1X]
[2025-06-15 14:33:52,217] [INFO] [rayshiba cleared 4 messages in channel test-n1x.]
[2025-06-15 14:34:18,234] [ERROR] [Ignoring exception in command clear]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 1021, in invoke
    await self.prepare(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 938, in prepare
    await self._parse_arguments(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 845, in _parse_arguments
    transformed = await self.transform(ctx, param, attachments)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 697, in transform
    raise MissingRequiredArgument(param)
discord.ext.commands.errors.MissingRequiredArgument: amount is a required argument that is missing.
[2025-06-15 14:34:57,945] [INFO] [rayshiba cleared 1 messages in channel test-n1x.]
[2025-06-15 14:54:57,163] [INFO] [logging in using static token]
[2025-06-15 14:54:58,186] [INFO] [Shard ID None has connected to Gateway (Session ID: fa207c380e3893cb2f98cf52e3d0895c).]
[2025-06-15 14:55:00,198] [INFO] [Logged in as N1X]
[2025-06-15 14:55:00,198] [ERROR] [Ignoring exception in on_ready]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\client.py", line 481, in _run_event
    await coro(*args, **kwargs)
  File "c:\Users\Ray\Desktop\N1X Bot\main.py", line 20, in on_ready
    RoleID = discord.role.id(RoleName)
             ^^^^^^^^^^^^^^^
AttributeError: module 'discord.role' has no attribute 'id'
[2025-06-15 16:48:34,782] [INFO] [logging in using static token]
[2025-06-15 16:48:35,853] [INFO] [Shard ID None has connected to Gateway (Session ID: ae528e6bfa26e211347a1e0a055c25e3).]
[2025-06-15 16:48:37,864] [INFO] [Logged in as N1X]
[2025-06-15 16:48:48,071] [ERROR] [Ignoring exception in command None]
discord.ext.commands.errors.CommandNotFound: Command "get_avatar" is not found
[2025-06-15 17:15:07,342] [INFO] [logging in using static token]
[2025-06-15 17:15:08,400] [INFO] [Shard ID None has connected to Gateway (Session ID: 206c53a51632c6565ea45244f42c4f11).]
[2025-06-15 17:15:10,420] [INFO] [Logged in as N1X]
[2025-06-15 17:15:15,991] [ERROR] [Ignoring exception in command banlist]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ray\Desktop\N1X Bot\Commands\moderation.py", line 59, in banlist
    bans = await ctx.guild.bans()
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object async_generator can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object async_generator can't be used in 'await' expression
[2025-06-15 17:17:18,399] [INFO] [logging in using static token]
[2025-06-15 17:17:20,969] [INFO] [Shard ID None has connected to Gateway (Session ID: 29d406a5d3f16f5684a9f29449f5b787).]
[2025-06-15 17:17:22,973] [INFO] [Logged in as N1X]
[2025-06-15 17:17:24,467] [ERROR] [Ignoring exception in command banlist]
Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\Ray\Desktop\N1X Bot\Commands\moderation.py", line 59, in banlist
    bans = await ctx.guild.bans()
           ^^^^^^^^^^^^^^^^^^^^^^
TypeError: object async_generator can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\bot.py", line 1366, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ray\AppData\Local\Programs\Python\Python313\Lib\site-packages\discord\ext\commands\core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: object async_generator can't be used in 'await' expression
[2025-06-15 17:41:48,124] [INFO] [logging in using static token]
[2025-06-15 17:41:49,193] [INFO] [Shard ID None has connected to Gateway (Session ID: f8e884132d79cd680d511bf4cb190c0b).]
[2025-06-15 17:41:51,203] [INFO] [Logged in as N1X]
[2025-06-15 18:09:10,952] [INFO] [logging in using static token]
[2025-06-15 18:09:12,098] [INFO] [Shard ID None has connected to Gateway (Session ID: e450d2f34e5ec9882e5db6e59117078a).]
[2025-06-15 18:09:14,101] [INFO] [Logged in as N1X]
[2025-06-15 18:11:23,269] [INFO] [logging in using static token]
[2025-06-15 18:11:24,368] [INFO] [Shard ID None has connected to Gateway (Session ID: 628a025a202d64eeb13793d252241417).]
[2025-06-15 18:11:26,390] [INFO] [Logged in as N1X]
[2025-06-15 18:12:23,334] [INFO] [logging in using static token]
[2025-06-15 18:12:24,474] [INFO] [Shard ID None has connected to Gateway (Session ID: 1d6f10b5e74f62c03c6da0862397d7f6).]
[2025-06-15 18:12:26,477] [INFO] [Logged in as N1X]
[2025-06-15 18:13:24,036] [INFO] [logging in using static token]
[2025-06-15 18:13:25,117] [INFO] [Shard ID None has connected to Gateway (Session ID: a6c873b52681ac3ab5316c45f6c39bfe).]
[2025-06-15 18:13:27,137] [INFO] [Logged in as N1X]
[2025-06-15 18:14:34,801] [INFO] [logging in using static token]
